[build]
  command   = "npm run build"
  publish   = ".netlify/functions-internal"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from   = "/*"
  to     = "/.netlify/functions/handler"
  status = 200
