[build]
  base    = "frontend"
  command = "npm run build"
  publish = ".netlify/static"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from   = "/*"
  to     = "/.netlify/functions/handler"
  status = 200
